Move tt++ executable path to variable

diff --git a/flexible_survival b/flexible_survival
--- a/flexible_survival
+++ b/flexible_survival
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # flexiblesurvival - A script for starting tintin++ sessions with a nice UI for flexiblesurvival.com
 # Copyright (C) 2018  Inutt - https://gitlab.com/inutt/flexible-survival-ui
@@ -17,7 +17,7 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
-set -o errexit -o pipefail -o nounset
+set -o pipefail -o nounset
 export COLORTERM='truecolor'
 
 export app_name='fs_mud' # Keep this consistent between scripts
@@ -112,6 +112,12 @@ fi
 
 export TMUX_CMD="tmux -L tmux_fs_socket -f ${fs_tmux_theme}"
 export TMUX_RELOAD="tmux -L tmux_fs_socket source-file ${fs_tmux_theme}"
+export TINTIN=${TINTIN:-tt++}
+which ${TINTIN} > /dev/null 2>&1
+if [[ $? -ne 0 ]]; then
+    echo "$0: Couldn't find tintin++ executable ${TINTIN}"
+    exit 1;
+fi
 
 # Set the character's sex symbol as otherwise it isn't available until the first status update
 if [[ -r ${data_dir}/status.json ]]; then
@@ -122,15 +128,20 @@ fi
 if [[ $(${TMUX_CMD} has-session -t "${fs_tmux_session_name}") ]]; then
     ${TMUX_CMD} attach-session -t "${fs_tmux_session_name}"
 else
-    ${TMUX_CMD} new-session -A -s "${fs_tmux_session_name}" -d -x ${max_width} -y ${max_height} tt++ ${app_dir}/scripts/main.tin
+    ${TMUX_CMD} new-session -A -s "${fs_tmux_session_name}" -d -x ${max_width} -y ${max_height} ${TINTIN} ${app_dir}/scripts/main.tin
     ${TMUX_CMD} list-panes -F "#{pane_pid}" > "${data_dir}/main.pid" # Store the PID of the main tintin session
+    kill -0 $(cat "${data_dir}/main.pid") > /dev/null 2>/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo "$0: Failed to start main tintin++ session"
+        exit 1;
+    fi
     ${app_dir}/scripts/update_status.pl --name "${fs_character}" # For initial setup
     ${TMUX_CMD} set-option -g aggressive-resize off
     ${TMUX_CMD} set-option -g set-titles on
     ${TMUX_CMD} set-option -g set-titles-string '#S'
-    ${TMUX_CMD} split-window -v -l ${chat_height} -b -t 0 tt++ "${app_dir}/scripts/chat_pane.tin"
+    ${TMUX_CMD} split-window -v -l ${chat_height} -b -t 0 ${TINTIN} "${app_dir}/scripts/chat_pane.tin"
     ${TMUX_CMD} split-window -h -l ${map_width} -b -t 1 "perl \"${app_dir}/scripts/status.pl\" 2> \"${data_dir}/status.err\""
-    ${TMUX_CMD} split-window -v -l ${map_height} -t 1 tt++ "${app_dir}/scripts/map_pane.tin"
+    ${TMUX_CMD} split-window -v -l ${map_height} -t 1 ${TINTIN} "${app_dir}/scripts/map_pane.tin"
 
     ${TMUX_CMD} select-pane -t 3
     ${TMUX_CMD} attach-session
